engines:
  pep8:
    enabled: true
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 40
          python_version: 3
  
ratings:
  paths:
    - "**.py"
