kind: pipeline
name: default
steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: quay.io
      repo: quay.io/natlibfi/annif
      tags: [latest]
    when:
      event: push
      branch: [issue278-dockerize-annif]
---
kind: pipeline
name: dev-image-deployment
steps:
  - name: docker-dev
    image: plugins/docker
    settings:
      dockerfile: Dockerfile-dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: quay.io
      repo: quay.io/natlibfi/annif
      tags: [dev]
    when:
      event: push
      branch: [issue278-dockerize-annif]
