kind: pipeline
name: default
steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: quay.io
      repo: quay.io/natlibfi/annif
      auto_tag: true
    when:
      event: push
      branch: [issue278-dockerize-annif]
