checks:
    python:
        code_rating: true
        duplicate_code: true

build:
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
    my-tests:
      tests:
        override:
          - true

