build:
    environment:
        python: 3.6.3
    dependencies:
        before:
            - pip install pipenv
            - pipenv install --dev --skip-lock
    tests:
        override:
            - pipenv run pytest
