checks:
  python:
    code_rating: true
    duplicate_code: true
build:
  environment:
    python: 3.6.3
  nodes:
    analysis:
      dependencies:
        override:
         - pip install pipenv
         - pipenv install --dev --skip-lock
      tests:
        override:
         - py-scrutinizer-run
