sudo: false
language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install pipenv
  - pipenv install --dev --skip-lock
  - travis_wait 30 python -m nltk.downloader punkt
script:
  - pytest --cov=./
after_success:
  - codecov
  - coveralls
notifications:
  slack: kansalliskirjasto:tyt7yhMrgqceJoKiSNt09nvV
