sudo: false
language: python
python:
  - "3.5"
cache: pip
install:
  - pip install -r requirements.txt
services:
  - elasticsearch
env:
  - FLASK_APP="annif/annif.py"
script:
  - pytest
after_success:
  - codecov
  - pytest --cov=./
