sudo: false
language: python
python:
  - "3.5"
cache: pip
install:
  - pip install -r requirements.txt
services:
  - elasticsearch
env:
  - FLASK_APP="annif.py"
script:
  - pytest
after_success:
  - codecov
  - coveralls
  - pytest --cov=./
notifications:
  slack: kansalliskirjasto:tyt7yhMrgqceJoKiSNt09nvV
