sudo: false
language: python
python:
  - "3.5"
cache: pip
install:
  - pip install -r requirements.txt
env:
  - FLASK_APP="annif/__init__.py"
script:
  - pytest --cov=./
after_success:
  - codecov
  - coveralls
notifications:
  slack: kansalliskirjasto:tyt7yhMrgqceJoKiSNt09nvV
