sudo: false
language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
services:
  - elasticsearch
before_script:
  - sleep 15
  - curl -XGET http://localhost:9200
script:
  - pytest
after_success:
  - codecov
  - pytest --cov=./
