version: "3"

services:

  gunicorn_server:
    restart: always
    image: quay.io/natlibfi/annif
    # volumes:
    #   - ${ANNIF_PROJECTS}:/annif-projects
    # user: ${UID}:${GID}
    command: ["gunicorn", "annif:create_app()", "--bind", "0.0.0.0:8000"]
    volumes:
      - annif-data:/annif-projects
    depends_on:
      - data

    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
        - node.labels.environment == test

  nginx:
    restart: always
    image: nginx
    volumes:
      - annif-data:/annif-projects
    # ports:
    #   - "80:80"
    depends_on:
      - gunicorn_server
    command: ["nginx", "-c", "/annif-projects/nginx.conf", "-g", "daemon off;"]

  # app:
  #   image: annif
  #   stdin_open: true
  #   tty: true
  #   command: bash
  #   volumes:
  #     - annif-data:/annif-projects

  data:
    image: annif-data
    volumes:
      - annif-data:/annif-projects
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
        - node.labels.environment == test

volumes:
  annif-data:
