version: "3"

services:

  annif_server:
    restart: always
    image: annif
    volumes:
      - ./projects.cfg.dist:/annif_projects/projects.cfg
    command: ["gunicorn", "annif:create_app()", "--bind", "0.0.0.0:8000"]


  nginx:
    restart: always
    build:
      context: annif/nginx/
    ## Instead of having own Dockerfile for nginx image, this could be used:
    #image: nginx:alpine
    #volumes:
    #  - ./annif/nginx/nginx.conf:/etc/nginx/nginx.conf
    #command: nginx #-c /etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - annif_server
