version: "3"

services:

  annif_server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-server

  nginx:
    restart: always
    build:
      context: annif/nginx/
    ## Instead of having own Dockerfile for nginx image, this could be used:
    #image: nginx:alpine
    #volumes:
    #  - ./annif/nginx/nginx.conf:/etc/nginx/nginx.conf
    #command: nginx #-c /etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - annif_server
