swagger: '2.0'
info:
  title: Annif REST API
  version: v1
schemes:
  - http
basePath: /v1/
parameters:
  projectidParam:
    name: projectid
    in: path
    description: project identifier
    required: true
    type: string
  subjectidParam:
    name: subjectid
    in: path
    description: subject identifier
    required: true
    type: string
paths:
  /projects:
    get:
      summary: get a list of projects
      produces:
        - application/json
      responses:
        '200':
          description: succesful operation
      tags:
        - Project administration
  '/projects/{projectid}':
    get:
      summary: show project information
      parameters:
        - $ref: '#/parameters/projectidParam'
      responses:
        '200':
          description: succesful operation
        '404':
          description: project not found
      tags:
        - Project administration
    put:
      summary: create or update project
      parameters:
        - $ref: '#/parameters/projectidParam'
      consumes:
        - application/json
      responses:
        '204':
          description: 'succesful operation, no content returned'
        '409':
          description: 'the project already exists, with incompatible settings'
      tags:
        - Project administration
    delete:
      summary: delete a project
      parameters:
        - $ref: '#/parameters/projectidParam'
      responses:
        '204':
          description: 'succesful operation, no content returned'
        '404':
          description: project not found
      tags:
        - Project administration
  '/projects/{projectid}/subjects':
    get:
      summary: get a list of all subjects defined for a project
      parameters:
        - $ref: '#/parameters/projectidParam'
      responses:
        '200':
          description: succesful operation
        '404':
          description: project not found
      tags:
        - Subject index administration
  '/projects/{projectid}/subjects/{subjectid}':
    get:
      summary: show subject information
      parameters:
        - $ref: '#/parameters/projectidParam'
        - $ref: '#/parameters/subjectidParam'
      produces:
        - application/json
      responses:
        '200':
          description: succesful operation
        '404':
          description: project or subject not found
      tags:
        - Subject index administration
    put:
      summary: create or update subject information
      parameters:
        - $ref: '#/parameters/projectidParam'
        - $ref: '#/parameters/subjectidParam'
      consumes:
        - application/json
      responses:
        '204':
          description: 'succesful operation, no content returned'
        '404':
          description: project or subject not found
      tags:
        - Subject index administration
    delete:
      summary: delete subject information
      parameters:
        - $ref: '#/parameters/projectidParam'
        - $ref: '#/parameters/subjectidParam'
      responses:
        '204':
          description: 'succesful operation, no content returned'
        '404':
          description: project or subject not found
      tags:
        - Subject index administration
  '/projects/{projectid}/analyze':
    post:
      summary: suggest subjects for a given text
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/projectidParam'
        - name: text
          in: formData
          description: input text
          required: true
          type: string
        - name: maxhits
          in: formData
          description: maximum number of results to return
          required: false
          type: integer
          default: 12
        - name: threshold
          in: formData
          description: >-
            minimum score threshold, expressed as a fraction of highest score,
            below which results will not be returned
          required: false
          type: number
          default: 0.45
      responses:
        '200':
          description: successful operation
      tags:
        - Automatic subject indexing
