swagger: '2.0'
info:
  title: Annif REST API
  version: v1
schemes:
  - http
basePath: /v1/
consumes:
  - application/json
produces:
  - application/json
parameters:
  project_id:
    name: project_id
    in: path
    description: project identifier
    required: true
    type: string
  subject_id:
    name: subject_id
    in: path
    description: subject identifier
    required: true
    type: string
paths:
  /projects:
    get:
      summary: get a list of projects
      operationId: annif.list_projects
      produces:
        - application/json
      responses:
        '200':
          description: succesful operation
      tags:
        - Project administration
  /projects/{project_id}:
    get:
      summary: show project information
      operationId: annif.show_project
      parameters:
        - $ref: '#/parameters/project_id'
      responses:
        '200':
          description: succesful operation
        '404':
          description: project not found
      tags:
        - Project administration
definitions:
  Project:
    description: A project definition
    properties:
      projectid:
        type: string
        example: my-project
      language:
        type: string
        example: en
      analyzer:
        type: string
        example: english
    required:
      - projectid
      - language
      - analyzer
  ProjectList:
    properties:
      projects:
        type: array
        items:
          $ref: '#/definitions/Project'
